### ISSUE TITLE
Tests fail on 1.9.3-p286

### ISSUE THREAD

**Issue by nedski** [ruby-bdb/bdb#7]
I was trying to get bdb working on a newer system and kept running into problems. Cloned this repo to run the test suite and got the following error repeatedly:

``` ruby
/home/xubuntu/dev/bdb/lib/bdb/environment.rb:60:in `block in env': undefined method `set_timeout' for # (NoMethodError)
        from /home/xubuntu/dev/bdb/lib/bdb/environment.rb:115:in `synchronize'
        from /home/xubuntu/dev/bdb/lib/bdb/environment.rb:49:in `env'
        from /home/xubuntu/dev/bdb/lib/bdb/environment.rb:91:in `block in transaction'
        from /home/xubuntu/dev/bdb/lib/bdb/environment.rb:120:in `block (2 levels) in synchronize'
        from :28:in `block in exclusive'
        from :10:in `synchronize'
        from :27:in `exclusive'
        from /home/xubuntu/dev/bdb/lib/bdb/environment.rb:120:in `block in synchronize'
...
```

BDB 5.1.25 on Xubuntu 12.04.

Not sure where to go from here... any idea what's causing this?

**Comment by DenisKnauf** [comment]
Tests are not tested, yet. These are old tests, i never used these. But tests should be fixed...
I'll look for it.
